name: Build & Deploy via Password SSH

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}
      DEPLOY_USER: ${{ vars.DEPLOY_USER }}
      DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Vite project
        run: npm run build

      # - name: Install sshpass
      #   run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Test SSH connection using password
        run: |
          sshpass -p "${{ vars.DEPLOY_SSH_PASSWORD }}" \
            ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" echo "SSH with password works"

      - name: Deploy via rsync using password
        run: |
          sshpass -p "${{ vars.DEPLOY_SSH_PASSWORD }}" \
            rsync -avz --delete \
              -e "ssh -o StrictHostKeyChecking=no" \
              dist/ "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/"
