name: Build & Deploy to Linode

on:
  push:
    branches: [main]          # adjust if you deploy from a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2 Set up Node (use the same major version you develop with)
      - name: Use Node 18 LTS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3 Install & build
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # 4 Prepare SSH key for rsync
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ vars.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ vars.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      # check ssh 
      - name: Inspect private key
        run: |
          set -eo pipefail
          head -3 ~/.ssh/id_ed25519 || true
          ssh-keygen -yf ~/.ssh/id_ed25519 || true   # exits 1 if the key can’t be parsed

      # 5 Sync dist/ to Linode
      - name: Deploy via rsync
        run: |
          rsync -avz --delete \
            dist/ \
            "${{ vars.DEPLOY_USER }}@${{ vars.DEPLOY_HOST }}:${{ vars.DEPLOY_PATH }}/"
