name: Build & Deploy to Linode

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}
      DEPLOY_USER: ${{ vars.DEPLOY_USER }}
      DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Vite project
        run: npm run build

      - name: Decode SSH private key from base64
        run: |
          mkdir -p ~/.ssh
          printf '%s' "${{ vars.DEPLOY_KEY_B64 }}" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
          ssh-keygen -yf ~/.ssh/id_ed25519 >/dev/null

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/id_ed25519 -oStrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" 'echo SSH works'

      - name: Deploy via rsync
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/id_ed25519 -oStrictHostKeyChecking=no" \
            dist/ "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/"
